import{a as E,S as $}from"./assets/vendor-CW10_Hpq.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const S="46991464-598feb9117dc71abe61f88b6f",q="https://pixabay.com/api/",x=15;async function h(t,a=1){const r=`${q}?key=${S}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${x}&page=${a}`,s=await E.get(r);if(s.status!==200)throw new Error("Failed to fetch images");return{images:s.data.hits.map(({webformatURL:e,largeImageURL:o,tags:l,likes:b,comments:L,views:w,downloads:v})=>({webformatURL:e,largeImageURL:o,tags:l,likes:b,comments:L,views:w,downloads:v})),totalHits:s.data.totalHits}}function g(t,a=!1){const r=document.querySelector(".image-gallery"),s=t.map(e=>`
        <div class="image-item">
            <a href="${e.largeImageURL}">
                <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
            </a>
            <div class="image-info">
                <h5 class ="text"> <span class="icon-data">💗 Likes: ${e.likes} </span></h5>
                <h5 class ="text"> <span class="icon-data">🗨️ Comments: ${e.comments}</span></h5>
                <h5 class ="text"><span class="icon-data">👀 Views: ${e.views}</span></h5>
                <h5 class ="text"><span class="icon-data">⬇️ Downloads: ${e.downloads}</span></h5>

            </div>
        </div>
    `).join("");a?r.insertAdjacentHTML("beforeend",s):r.innerHTML=s}function d(t){iziToast.show({title:"Error",message:t,position:"bottomCenter",color:"red"})}const y=document.querySelector(".search-form"),p=document.querySelector(".image-gallery"),u=document.querySelector(".loader"),n=document.createElement("button");n.classList.add("load-more");n.textContent="Load more";p.insertAdjacentElement("afterend",n);let f,c="",i=1,m=0;y.addEventListener("submit",async t=>{var a;if(t.preventDefault(),c=(a=y.querySelector(".search-form-input"))==null?void 0:a.value.trim(),!c){d("Please enter a valid search query");return}i=1,n.style.display="none",p.innerHTML="",u.style.display="block";try{const{images:r,totalHits:s}=await h(c,i);m=s,g(r),f=new $(".image-gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),f.refresh(),m>i*15&&(n.style.display="block")}catch(r){d(r.message)}finally{u.style.display="none"}});n.addEventListener("click",async()=>{i+=1,u.style.display="block";try{const{images:t}=await h(c,i);g(t,!0),f.refresh(),i*15>=m?(n.style.display="none",d("No more results could be found")):H()}catch(t){d(t.message)}finally{u.style.display="none"}});function H(){const{height:t}=p.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
